---

# Runs all dependencies


- name: Install dependencies
  become: true
  loop: "{{ dependencies[ansible_os_family] }}"
  when: item not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

...