---

- name: Create and configure ansible-nautilus
  hosts: client

  # TODO local testing only
  # debugger: on_failed

  roles:
    - role: ansible-nautilus
      tasks_from: main
      nautilus_state: present

...
